android.enableJetifier=true
android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.jvmargs=-Xmx8192m

# Versioning
VERSION_NAME=1.6.0
VERSION_CODE=13
APP_ID=org.fossify.contacts

# 沙箱内存有限
org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m
org.gradle.daemon=false
org.gradle.parallel=false
kotlin.daemon.jvmargs=-Xmx1024m
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.caching=true
