[versions]
#jetbrains
kotlin = "2.3.10"
#KSP
ksp = "2.3.6"
#Detekt
detekt = "1.23.8"
detektCompose = "0.6.2"
#AndroidX
androidx-swiperefreshlayout = "1.2.0"
#AutoFitTextView
autofittextview = "0.2.1"
#EzVCard
ezvcard = "0.12.2"
#IndicatorFastScroll
indicatorfastscroll = "4524cd0b61"
#Room
room = "2.8.4"
#Fossify
commons = "6.1.6"
#加密同步
okhttp = "4.12.0"
argon2kt = "1.6.0"
work = "2.10.0"
securityCrypto = "1.1.0-alpha06"
sqlcipher = "4.6.1"
androidxSqlite = "2.4.0"
androidxTestJunit = "1.2.1"
androidxTestRunner = "1.6.2"
#Gradle
gradlePlugins-agp = "9.1.0"
#build
app-build-compileSDKVersion = "36"
app-build-targetSDK = "36"
app-build-minimumSDK = "26"
app-build-javaVersion = "VERSION_17"
app-build-kotlinJVMTarget = "17"
[libraries]
#AndroidX
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
#AutoFitTextView
autofittextview = { module = "me.grantland:autofittextview", version.ref = "autofittextview" }
#EzVcard
ezvcard = { module = "com.googlecode.ez-vcard:ez-vcard", version.ref = "ezvcard" }
#IndicatorFastScroll
indicatorfastscroll = { module = "org.fossify:IndicatorFastScroll", version.ref = "indicatorfastscroll" }
#Room
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
#Compose
compose-detekt = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektCompose" }
#Fossify
fossify-commons = { module = "org.fossify:commons", version.ref = "commons" }
#加密同步
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
argon2kt = { module = "com.lambdapioneer.argon2kt:argon2kt", version.ref = "argon2kt" }
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
sqlcipher = { module = "net.zetetic:sqlcipher-android", version.ref = "sqlcipher" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "androidxSqlite" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestJunit" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
[bundles]
room = [
    "androidx-room-ktx",
    "androidx-room-runtime",
]
[plugins]
android = { id = "com.android.application", version.ref = "gradlePlugins-agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
